version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: nX8enxe0n
      MYSQL_DATABASE: fanscrm
    ports:
      - '10568:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Добавление скрипта инициализации

volumes:
  mysql_data:
